name: task_management_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4  
  flutter_native_splash: ^2.4.6
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"
flutter_native_splash:
  color: "#ffffff"
  image: assets/app_logo.png
  android_12:
    image: assets/app_logo.png
    color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
